### ExpBottle

### Translatable messages
noPermission: '&cYou do not have the right permissions to execute this command.'
cmdUsageUser: '&aUse &r/xpbottle <XP/All> &ato withdraw experience. You currently have &r%playerxp% &aXP.'
cmdUsageAdmin: '&aUse &r/xpbottle <XP/All/Give> [Player] [XP] &ato withdraw or give XP. You currently have &r%playerxp% &aXP. There is a &r%tax%% &atax on all withdraws.'
notEnoughXp: '&cYou do not have the sufficient experience. You need %taxprice% to withdraw %xp%'
xpNotANumber: '&cXP must be a number.'
overMaxUnderMin: '&cYou cant withdraw more than &r%maxxp% &cXP or less than &r%minxp% &cXP.'
successfulWithdraw: '&aYou successfully withdrew &r%xp% &aXP.'
reloadSuccessful: '&aYou successfully reloaded the config.'
xpBottleGive: '&aYou gave &r%receiverdisplayname% &aan XP Bottle with &r%xp% &aXP.'
xpBottleReceive: '%playerdisplayname% &agave you an XP Bottle with &r%xp% &aXP.'
giveYourselfXp: '&aYou gave yourself an XP Bottle with &r%xp% &aXP.'
playerNotOnline: '&cSpecified player is not online.'

### XP Bottle informasjon
# One of the lines in lore MUST use %xp%
xpBottleName: '&aXP Bottle'
xpBottleLore:
- '&9Creator: &r%playerdisplayname%'
- '&9XP: &a%xp%'

### Minimum and maximum amount of XP you can withdraw
minXp: 50
maxXp: 100000

### Tax on xp bottle
tax: false
# Tax amount. 0.3 = 30% tax
taxAmount: 0.3

### Aliases

## Simply add a new line with a new alias e.g:
# exampleAliases:
# - 'alias1'
# - 'alias2'

#Aliases to the actual xpbottle command
commandAliases:
- 'expbottle'

#Aliases to the "give" function
giveAliases:
- 'i'

#Aliases to the "all" function
allAliases:
- 'everything'

#Aliases to the "reload" function
reloadAliases:
- 'rel'