# ExpBottle

# Translatable messages

# List of tags:
# Universal tags (which can be used everywhere): %playername%, %playerdisplayname%, %minxp%, %maxxp%, %playerxp%
# Conditional tags (which can only be used ): %missingxp%, %xp%

# Messages which can be translated
noPermission: '&cYou do not have the right permissions to execute this command'
cmdUsage: '&aUse &r/xpbottle <XP> &ato withdraw experience. You currently have &r%playerxp% &axp.'
notEnoughXp: '&cYou do not have the sufficient experience'
xpNotANumber: '&cXP must be a number'
overMaxUnderMin: '&cYou cant withdraw more than &r%maxxp% &cXP or less than &r%minxp% &cXP'
successfulWithdraw: '&aYou have successfully withdrawed &r%xp% &aXP'
reloadSuccessful: '&aYou successfully reloaded the config'

# XP Bottle informasjon
xpBottleName: '&aXP Bottle'
xpBottleLore:
- '&9Creator: &r%playerdisplayname%'
- '&9XP: &a%xp%'

# Minimum and maximum amount of XP you can withdraw
minXp: 50
maxXp: 100000

# Aliases
aliases: